const GET_STUDENTS = "GET_STUDENTS";
const GET_TEACHERS = "GET_TEACHERS";
const GET_SUBJECTS = "GET_SUBJECTS";
const GET_PERSON = "GET_PERSON";
const GET_REPORT = "GET_REPORT";
const GET_SUBJECT = "GET_SUBJECT";

export { GET_STUDENTS, GET_TEACHERS, GET_SUBJECTS, GET_PERSON, GET_REPORT, GET_SUBJECT };
